name: Publish on PyPI on Release

on:
  release:
    types: [published]

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: pypi
    
    steps:
      - uses: actions/checkout@v4
  
      - name: Download release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Create dist directory if it doesn't exist
          mkdir -p dist
          
          # Download .tar.gz and .whl files from the release
          gh release download ${{ github.ref_name }} \
            --pattern "*.tar.gz" \
            --pattern "*.whl" \
            --dir dist
        
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true